/**
 * Generated by scripts/vendor-bundled-file-icons.mjs — do not edit by hand.
 *
 * Fallback icon map for VS Code installations without a usable file icon theme. Icons are a
 * subset of Material Icon Theme (MIT), vendored under apps/vscode/assets/icons with the license
 * alongside; see NOTICE.md there. Shape matches an icon-theme JSON so the runtime can resolve
 * it with the same code path as any installed theme.
 */
import type { IconThemeJson } from "./fileIconResolve.js";

export const BUNDLED_ICONS: IconThemeJson = {
  "iconDefinitions": {
    "audio": {
      "iconPath": "audio.svg"
    },
    "c": {
      "iconPath": "c.svg"
    },
    "changelog": {
      "iconPath": "changelog.svg"
    },
    "clojure": {
      "iconPath": "clojure.svg"
    },
    "cmake": {
      "iconPath": "cmake.svg"
    },
    "console": {
      "iconPath": "console.svg"
    },
    "cpp": {
      "iconPath": "cpp.svg"
    },
    "csharp": {
      "iconPath": "csharp.svg"
    },
    "css": {
      "iconPath": "css.svg"
    },
    "dart": {
      "iconPath": "dart.svg"
    },
    "database": {
      "iconPath": "database.svg"
    },
    "diff": {
      "iconPath": "diff.svg"
    },
    "docker": {
      "iconPath": "docker.svg"
    },
    "document": {
      "iconPath": "document.svg"
    },
    "editorconfig": {
      "iconPath": "editorconfig.svg"
    },
    "elixir": {
      "iconPath": "elixir.svg"
    },
    "exe": {
      "iconPath": "exe.svg"
    },
    "file": {
      "iconPath": "file.svg"
    },
    "folder": {
      "iconPath": "folder.svg"
    },
    "folder-config": {
      "iconPath": "folder-config.svg"
    },
    "folder-dist": {
      "iconPath": "folder-dist.svg"
    },
    "folder-docs": {
      "iconPath": "folder-docs.svg"
    },
    "folder-lib": {
      "iconPath": "folder-lib.svg"
    },
    "folder-public": {
      "iconPath": "folder-public.svg"
    },
    "folder-resource": {
      "iconPath": "folder-resource.svg"
    },
    "folder-scripts": {
      "iconPath": "folder-scripts.svg"
    },
    "folder-src": {
      "iconPath": "folder-src.svg"
    },
    "folder-test": {
      "iconPath": "folder-test.svg"
    },
    "git": {
      "iconPath": "git.svg"
    },
    "go": {
      "iconPath": "go.svg"
    },
    "gradle": {
      "iconPath": "gradle.svg"
    },
    "groovy": {
      "iconPath": "groovy.svg"
    },
    "h": {
      "iconPath": "h.svg"
    },
    "hcl": {
      "iconPath": "hcl.svg"
    },
    "hcl_light": {
      "iconPath": "hcl_light.svg"
    },
    "hex": {
      "iconPath": "hex.svg"
    },
    "hpp": {
      "iconPath": "hpp.svg"
    },
    "html": {
      "iconPath": "html.svg"
    },
    "image": {
      "iconPath": "image.svg"
    },
    "java": {
      "iconPath": "java.svg"
    },
    "javascript": {
      "iconPath": "javascript.svg"
    },
    "json": {
      "iconPath": "json.svg"
    },
    "jupyter": {
      "iconPath": "jupyter.svg"
    },
    "kotlin": {
      "iconPath": "kotlin.svg"
    },
    "less": {
      "iconPath": "less.svg"
    },
    "license": {
      "iconPath": "license.svg"
    },
    "lock": {
      "iconPath": "lock.svg"
    },
    "log": {
      "iconPath": "log.svg"
    },
    "lua": {
      "iconPath": "lua.svg"
    },
    "makefile": {
      "iconPath": "makefile.svg"
    },
    "markdown": {
      "iconPath": "markdown.svg"
    },
    "mdx": {
      "iconPath": "mdx.svg"
    },
    "npm": {
      "iconPath": "npm.svg"
    },
    "objective-c": {
      "iconPath": "objective-c.svg"
    },
    "objective-cpp": {
      "iconPath": "objective-cpp.svg"
    },
    "pdf": {
      "iconPath": "pdf.svg"
    },
    "php": {
      "iconPath": "php.svg"
    },
    "powershell": {
      "iconPath": "powershell.svg"
    },
    "prolog": {
      "iconPath": "prolog.svg"
    },
    "proto": {
      "iconPath": "proto.svg"
    },
    "python": {
      "iconPath": "python.svg"
    },
    "r": {
      "iconPath": "r.svg"
    },
    "react": {
      "iconPath": "react.svg"
    },
    "react_ts": {
      "iconPath": "react_ts.svg"
    },
    "readme": {
      "iconPath": "readme.svg"
    },
    "ruby": {
      "iconPath": "ruby.svg"
    },
    "rust": {
      "iconPath": "rust.svg"
    },
    "sass": {
      "iconPath": "sass.svg"
    },
    "scala": {
      "iconPath": "scala.svg"
    },
    "settings": {
      "iconPath": "settings.svg"
    },
    "svelte": {
      "iconPath": "svelte.svg"
    },
    "svg": {
      "iconPath": "svg.svg"
    },
    "swift": {
      "iconPath": "swift.svg"
    },
    "table": {
      "iconPath": "table.svg"
    },
    "terraform": {
      "iconPath": "terraform.svg"
    },
    "toml": {
      "iconPath": "toml.svg"
    },
    "toml_light": {
      "iconPath": "toml_light.svg"
    },
    "tune": {
      "iconPath": "tune.svg"
    },
    "typescript": {
      "iconPath": "typescript.svg"
    },
    "video": {
      "iconPath": "video.svg"
    },
    "vue": {
      "iconPath": "vue.svg"
    },
    "xml": {
      "iconPath": "xml.svg"
    },
    "yaml": {
      "iconPath": "yaml.svg"
    },
    "yarn": {
      "iconPath": "yarn.svg"
    },
    "zip": {
      "iconPath": "zip.svg"
    }
  },
  "file": "file",
  "folder": "folder",
  "fileExtensions": {
    "sh": "console",
    "bash": "console",
    "zsh": "console",
    "fish": "console",
    "py": "python",
    "pyw": "python",
    "js": "javascript",
    "mjs": "javascript",
    "cjs": "javascript",
    "jsx": "react",
    "ts": "typescript",
    "mts": "typescript",
    "tsx": "react_ts",
    "json": "json",
    "md": "markdown",
    "mdx": "mdx",
    "yml": "yaml",
    "yaml": "yaml",
    "toml": "toml",
    "ini": "settings",
    "cfg": "settings",
    "conf": "settings",
    "env": "tune",
    "log": "log",
    "txt": "document",
    "csv": "table",
    "tsv": "table",
    "xml": "xml",
    "svg": "svg",
    "html": "html",
    "htm": "html",
    "css": "css",
    "scss": "sass",
    "sass": "sass",
    "less": "less",
    "go": "go",
    "rs": "rust",
    "java": "java",
    "kt": "kotlin",
    "kts": "kotlin",
    "cs": "csharp",
    "c": "c",
    "h": "h",
    "cpp": "cpp",
    "hpp": "hpp",
    "cc": "cpp",
    "php": "php",
    "rb": "ruby",
    "swift": "swift",
    "scala": "scala",
    "vue": "vue",
    "svelte": "svelte",
    "sql": "database",
    "ps1": "powershell",
    "bat": "console",
    "r": "r",
    "dart": "dart",
    "lua": "lua",
    "pl": "prolog",
    "proto": "proto",
    "tf": "terraform",
    "hcl": "hcl",
    "gradle": "gradle",
    "cmake": "cmake",
    "ipynb": "jupyter",
    "lock": "lock",
    "patch": "git",
    "diff": "diff",
    "tar": "zip",
    "gz": "zip",
    "zip": "zip",
    "7z": "zip",
    "rar": "zip",
    "pdf": "pdf",
    "png": "image",
    "jpg": "image",
    "jpeg": "image",
    "gif": "image",
    "webp": "image",
    "mp4": "video",
    "mov": "video",
    "mp3": "audio",
    "wav": "audio",
    "flac": "audio",
    "bin": "hex",
    "exe": "exe",
    "m": "objective-c",
    "mm": "objective-cpp",
    "ex": "elixir",
    "exs": "elixir",
    "clj": "clojure",
    "groovy": "groovy"
  },
  "fileNames": {
    "dockerfile": "docker",
    "makefile": "makefile",
    "cmakelists.txt": "cmake",
    ".gitignore": "git",
    ".gitattributes": "git",
    ".gitmodules": "git",
    ".npmrc": "npm",
    ".yarnrc": "yarn",
    ".editorconfig": "editorconfig",
    "license": "license",
    "license.txt": "license",
    "readme": "readme",
    "readme.md": "readme",
    "changelog": "changelog",
    "changelog.md": "changelog"
  },
  "folderNames": {
    "src": "folder-src",
    "lib": "folder-lib",
    "bin": "folder-dist",
    "test": "folder-test",
    "tests": "folder-test",
    "docs": "folder-docs",
    "doc": "folder-docs",
    "assets": "folder-resource",
    "public": "folder-public",
    "config": "folder-config",
    "scripts": "folder-scripts"
  },
  "light": {
    "fileExtensions": {
      "toml": "toml_light",
      "hcl": "hcl_light"
    }
  }
};
